### PR TITLE
Merge pull request #5 from kalviumcommunity/main

### PR DESCRIPTION
**Pull request by a5h101**
Merge pull request #5 from a5h101/main

### CODE REVIEW

**Review by PatelNeelMahesh — COMMENTED** [review]
Akash, we don't see any files here, it's empty.

**Comment by a5h101** [comment]
day 5- mapping the item details page. Removing all hard coded cards

**Comment by a5h101** [comment]
day#5
Mapping the json files and displaying the itemDetails page, removing all the hard coded cards.

**Review by PatelNeelMahesh — APPROVED** [review]

**Comment by PatelNeelMahesh** [comment]
Update the default react readme file with the capstone description and figma file, along with the topics covered in capstone. https://github.com/kalviumcommunity/openbadgx

**Review by PatelNeelMahesh — CHANGES_REQUESTED** [review]
Akash, you need to merge pull request before pushing new changes.

**Pull request merged**
